// Bundle and send a candidate pack to a client.
//
// The pack is composed of:
//   - A short cover-note email (recruiter intro + optional personal
//     message). No inline scoring dump anymore; the report itself goes
//     out as a PDF attachment so the client gets a single artefact they
//     can forward, archive, or print.
//   - PRODICTA-Candidate-Report.pdf (always attached) — the full client-
//     facing assessment report generated by /api/.../candidate-brief-pdf.
//   - CV / Cover Letter from candidate_documents storage (each attached
//     when the recruiter has uploaded it on the candidate report).
//   - PRODICTA-Success-Plan.pdf (attached only when include_coaching_plan
//     is true on the request body, default false). Generated by
//     /api/.../success-plan-pdf.
//
// Backwards compatibility: any caller that omits include_coaching_plan
// gets the old behaviour minus the inline scoring dump (which is now in
// the report PDF). The route never throws when an optional PDF
// generator returns 404; it logs and continues so the recruiter still
// gets the rest of the bundle.

import { NextResponse } from 'next/server'
import { Resend } from 'resend'
import { createServerSupabaseClient, createServiceClient } from '@/lib/supabase-server'
import { EMAIL_FROM } from '@/lib/email-sender'

// Pull a PDF from one of our internal route handlers. Forwards the
// caller's session cookie so the GET handler authenticates as the
// agency user, then returns either a Buffer or null when the route
// reports nothing to send (e.g. no onboarding_plan yet).
async function fetchInternalPdf(siteUrl, path, cookieHeader) {
  try {
    const res = await fetch(`${siteUrl}${path}`, { headers: { cookie: cookieHeader || '' } })
    if (!res.ok) {
      console.warn(`[send-candidate-pack] internal PDF ${path} returned ${res.status}`)
      return null
    }
    const arr = await res.arrayBuffer()
    return Buffer.from(arr)
  } catch (e) {
    console.warn(`[send-candidate-pack] internal PDF ${path} fetch failed:`, e?.message)
    return null
  }
}

export async function POST(request) {
  try {
    const body = await request.json()
    const { candidateId, clientEmail, message } = body
    // Backwards-compat: missing flag falls through to false so legacy
    // callers continue to get the bundle without the 90-Day Plan.
    const includeCoachingPlan = !!body?.include_coaching_plan

    if (!candidateId || !clientEmail) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 })
    }

    const supabase = createServerSupabaseClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return NextResponse.json({ error: 'Unauthorised' }, { status: 401 })

    const adminClient = createServiceClient()

    // Fetch all required data in parallel
    const [
      { data: candidate },
      { data: profile },
      { data: docList },
    ] = await Promise.all([
      adminClient.from('candidates').select('id, name, user_id, completed_at, assessment_id, assessments(id, role_title)').eq('id', candidateId).eq('user_id', user.id).single(),
      adminClient.from('users').select('company_name, account_type').eq('id', user.id).maybeSingle(),
      adminClient.from('candidate_documents').select('*').eq('candidate_id', candidateId).eq('user_id', user.id),
    ])

    if (!candidate) return NextResponse.json({ error: 'Candidate not found' }, { status: 404 })

    const companyName = profile?.company_name || 'Your recruiter'
    const roleTitle   = candidate.assessments?.role_title || 'the role'
    const assessmentId = candidate.assessment_id || candidate.assessments?.id
    const candName = candidate.name || 'Candidate'
    const safeFileName = candName.replace(/\s+/g, '-')
    const completedAt = candidate.completed_at
      ? new Date(candidate.completed_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
      : null

    // ── ASSEMBLE ATTACHMENTS ──
    const attachments = []
    const cookieHeader = request.headers.get('cookie') || ''
    const siteUrl = process.env.NEXT_PUBLIC_SITE_URL
      || process.env.NEXT_PUBLIC_APP_URL
      || 'https://app.prodicta.co.uk'

    // 1. Always attach the full PRODICTA assessment report PDF.
    if (assessmentId) {
      const reportPdf = await fetchInternalPdf(siteUrl, `/api/assessment/${assessmentId}/candidate/${candidateId}/candidate-brief-pdf`, cookieHeader)
      if (reportPdf) {
        attachments.push({
          filename: `PRODICTA-Candidate-Report-${safeFileName}.pdf`,
          content: reportPdf,
        })
      }
    }

    // 2. Optionally attach the 90-Day Success Plan PDF.
    if (includeCoachingPlan && assessmentId) {
      const planPdf = await fetchInternalPdf(siteUrl, `/api/assessment/${assessmentId}/candidate/${candidateId}/success-plan-pdf`, cookieHeader)
      if (planPdf) {
        attachments.push({
          filename: `PRODICTA-Success-Plan-${safeFileName}.pdf`,
          content: planPdf,
        })
      }
    }

    // 3. Attach uploaded CV / Cover Letter from storage.
    for (const doc of (docList || [])) {
      try {
        const { data: blob } = await adminClient.storage.from('candidate-documents').download(doc.file_path)
        if (blob) {
          const arrayBuffer = await blob.arrayBuffer()
          const label = doc.doc_type === 'cv' ? 'CV' : 'Cover-Letter'
          attachments.push({
            filename: `${label}-${safeFileName}.pdf`,
            content: Buffer.from(arrayBuffer),
          })
        }
      } catch (e) {
        console.error(`[send-candidate-pack] failed to download ${doc.doc_type}:`, e)
      }
    }

    // ── COVER NOTE EMAIL ──
    // Short, professional cover note pointing at the attachments. No
    // inline scoring dump; the report PDF carries that. Personal
    // message renders as an italic blockquote when provided.
    const safeName = candName
    const personalMessageBlock = message && message.trim()
      ? `<div style="background:#f7f9fb;border-left:3px solid #00BFA5;padding:14px 18px;margin:0 0 22px;border-radius:0 8px 8px 0;font-size:14px;color:#0f2137;line-height:1.6;font-style:italic;">${message.trim().replace(/</g, '&lt;')}</div>`
      : ''
    const coachingLine = includeCoachingPlan
      ? `<li style="margin-bottom:6px;">90-Day Success Plan (PDF)</li>`
      : ''
    const cvLine = (docList || []).some(d => d.doc_type === 'cv') ? `<li style="margin-bottom:6px;">CV / Résumé (PDF)</li>` : ''
    const clLine = (docList || []).some(d => d.doc_type === 'cover_letter') ? `<li style="margin-bottom:6px;">Cover letter (PDF)</li>` : ''

    const html = `
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#f7f9fb;font-family:'Outfit',system-ui,sans-serif;color:#0f2137;">
  <div style="max-width:600px;margin:40px auto;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08);">

    <div style="background:#0f2137;padding:24px 36px;">
      <div style="color:#00BFA5;font-size:20px;font-weight:800;letter-spacing:-0.3px;">PRODICTA</div>
      <div style="color:rgba(255,255,255,0.55);font-size:12px;margin-top:2px;">Candidate report</div>
    </div>

    <div style="padding:32px 36px;">
      <p style="font-size:15px;color:#0f2137;margin:0 0 14px;line-height:1.6;">
        Please find attached the assessment report for <strong>${safeName}</strong>${roleTitle ? ` for the <strong>${roleTitle}</strong> position` : ''}.
      </p>
      ${completedAt ? `<p style="font-size:14px;color:#5e6b7f;margin:0 0 18px;">Assessment completed ${completedAt}.</p>` : ''}

      ${personalMessageBlock}

      <div style="background:#f0fdf8;border:1px solid #99e6d9;border-radius:10px;padding:14px 18px;margin:0 0 22px;">
        <div style="font-size:11px;font-weight:700;color:#00897b;text-transform:uppercase;letter-spacing:0.06em;margin-bottom:8px;">Attached</div>
        <ul style="margin:0;padding:0 0 0 18px;color:#0f2137;font-size:13.5px;line-height:1.6;">
          <li style="margin-bottom:6px;">Full PRODICTA assessment report (PDF)</li>
          ${cvLine}
          ${clLine}
          ${coachingLine}
        </ul>
      </div>

      <p style="font-size:13.5px;color:#5e6b7f;margin:0;line-height:1.6;">
        The report covers hiring recommendation, Pressure-Fit profile, top strengths, watch-outs, and tailored interview questions you can use directly. Reply to this email if you would like to discuss the candidate.
      </p>
    </div>

    <div style="background:#f7f9fb;padding:16px 36px;border-top:1px solid #e4e9f0;">
      <p style="font-size:12px;color:#94a1b3;margin:0;text-align:center;">
        Prepared by <strong style="color:#0f2137;">${companyName}</strong> using
        <strong style="color:#00BFA5;">PRODICTA</strong> work simulation assessments.
      </p>
    </div>
  </div>
</body>
</html>`

    const resend = new Resend(process.env.RESEND_API_KEY)
    await resend.emails.send({
      from: EMAIL_FROM,
      to: [clientEmail],
      subject: `Candidate report: ${safeName} | ${roleTitle}`,
      html,
      ...(attachments.length ? { attachments } : {}),
    })

    return NextResponse.json({ success: true, attachments: attachments.length })
  } catch (err) {
    console.error('Send candidate pack error:', err)
    return NextResponse.json({ error: err.message }, { status: 500 })
  }
}
