// Static blog posts. Move to a CMS later if needed.

export const BLOG_POSTS = [
  {
    slug: 'employment-rights-act-2025-what-employers-need-to-know',
    title: 'The Employment Rights Act 2025: What Every Employer Needs to Know',
    date: '2026-04-08',
    dateLabel: '8 April 2026',
    metaDescription: 'The Employment Rights Act 2025 changes everything for UK employers. Day-one unfair dismissal rights, no compensation cap. Here is what you need to know and how to prepare.',
    body: [
      { type: 'p', text: 'The Employment Rights Act 2025 is the most significant change to UK employment law in a generation. If you employ people in the UK, it affects you. If you hire people, it changes how you should be doing it. And if you are not preparing now, you are running out of time.' },
      { type: 'p', text: 'Here is what you need to know.' },
      { type: 'h2', text: 'What is the Employment Rights Act 2025?' },
      { type: 'p', text: 'The Employment Rights Act 2025 is new UK legislation that strengthens employee protections and increases employer accountability. It was passed in 2025 and the key changes take effect from January 2027.' },
      { type: 'p', text: 'The headline changes are:' },
      { type: 'p', text: 'The qualifying period for unfair dismissal claims drops from two years to six months. This means employees will be able to bring an unfair dismissal claim after just six months of employment, down from the current two-year requirement.' },
      { type: 'p', text: 'The statutory compensation cap for unfair dismissal is being removed. Currently, compensation is capped at the lower of 12 months pay or a statutory maximum. Under the new rules, there is no cap. A tribunal can award whatever it considers just and equitable.' },
      { type: 'p', text: 'A new Fair Work Agency will be established to enforce employment rights, including investigating complaints and taking enforcement action against employers.' },
      { type: 'h2', text: 'What does this mean in practice?' },
      { type: 'p', text: 'For employers, the practical impact is significant. Every person you hire from January 2027 onwards can take you to tribunal after just six months. There is no cap on what they can claim. And the burden of proof falls on you to demonstrate that any dismissal was fair.' },
      { type: 'p', text: 'This means three things:' },
      { type: 'p', text: 'First, your hiring decisions need to be documented and defensible. If you hire someone and later dismiss them during their first six months, a tribunal will ask: what evidence do you have that this was a fair hiring decision? What criteria did you use? How did you assess the candidate?' },
      { type: 'p', text: 'Second, your probation process needs to be structured and evidenced. You cannot simply dismiss someone during probation and say it was not working out. You need to document what was expected, what support was provided, and why the employee did not meet the required standard.' },
      { type: 'p', text: 'Third, the cost of a bad hire just went up significantly. A bad hire has always been expensive: recruitment fees, training, lost productivity, team disruption. Now you can add uncapped tribunal compensation to that list.' },
      { type: 'h2', text: 'Who does this affect?' },
      { type: 'p', text: 'Every employer in the UK. Every recruitment agency placing candidates. Every HR team making hiring decisions.' },
      { type: 'p', text: 'Small businesses are particularly exposed because they often lack formal hiring processes and documented assessment criteria. A small business that hires based on a CV and an informal chat has very little evidence to present if a tribunal asks how the hiring decision was made.' },
      { type: 'p', text: 'Recruitment agencies face a different risk. When a placement fails, the client will increasingly ask what evidence the agency had that this candidate was suitable. Agencies that cannot answer that question with data will lose clients to agencies that can.' },
      { type: 'h2', text: 'What should you do now?' },
      { type: 'p', text: 'The changes take effect from January 2027, but the hiring decisions you make today will be tested under the new rules. A candidate hired in June 2026 reaches their six-month mark in December 2026, just weeks before the new legislation takes effect.' },
      { type: 'h3', text: '1. Audit your hiring process' },
      { type: 'p', text: 'Look at every hire you have made in the past year. For each one, ask: could I demonstrate to a tribunal exactly why this candidate was selected? If your evidence is limited to good CV and interviewed well, you have a gap.' },
      { type: 'h3', text: '2. Move to objective, documented assessment' },
      { type: 'p', text: 'Structured interviews are a start, but they still rely on subjective judgement. Scenario-based assessment, where candidates are tested on realistic work tasks specific to the role, produces documented evidence that is tied directly to the job description and can withstand tribunal scrutiny.' },
      { type: 'h3', text: '3. Structure your probation process' },
      { type: 'p', text: 'Every new hire should have documented objectives, regular check-ins, and a clear evidence trail throughout their probation period. If you need to dismiss someone, you need to show you gave them a fair opportunity to succeed.' },
      { type: 'h3', text: '4. Prepare now, not in January 2027' },
      { type: 'p', text: 'The companies that prepare now will be protected. The companies that wait will be scrambling. The cost of preparation is small compared to the cost of an uncapped tribunal claim.' },
      { type: 'p', text: 'PRODICTA predicts probation outcomes before you make the offer. Try the free risk report tool at prodicta.co.uk or explore a demo report at prodicta.co.uk/demo.' },
    ],
  },

  {
    slug: 'the-real-cost-of-a-bad-hire-uk-2026',
    title: 'The Real Cost of a Bad Hire in the UK (2026)',
    date: '2026-04-08',
    dateLabel: '8 April 2026',
    metaDescription: 'A bad hire costs between 30,000 and 50,000 pounds. But the real number is higher. Here is the full breakdown including the new tribunal risk under ERA 2025.',
    body: [
      { type: 'p', text: 'Everyone talks about the cost of a bad hire. The numbers most commonly cited are between 30,000 and 50,000 pounds. But where do those numbers actually come from? And are they accurate?' },
      { type: 'p', text: 'The honest answer is that the real cost is almost certainly higher than most employers realise. Here is the full breakdown.' },
      { type: 'h2', text: 'The direct costs' },
      { type: 'h3', text: 'Recruitment fees' },
      { type: 'p', text: 'If you used a recruitment agency, the fee is typically 15 to 25 per cent of the first year salary. For a role paying 35,000 pounds, that is between 5,250 and 8,750 pounds. Gone.' },
      { type: 'h3', text: 'Advertising' },
      { type: 'p', text: 'Job adverts on major boards cost between 200 and 500 pounds per listing. Most roles require multiple listings across multiple platforms. Typical spend: 500 to 1,500 pounds.' },
      { type: 'h3', text: 'Training and onboarding' },
      { type: 'p', text: 'The average UK employer spends between 1,000 and 3,000 pounds on formal training for a new hire. Add the cost of informal training: the time other team members spend showing the new person how things work, answering questions, and correcting mistakes. For a typical office-based role, this adds another 2,000 to 5,000 pounds in lost productivity from the people doing the training.' },
      { type: 'h3', text: 'Salary paid for work not delivered' },
      { type: 'p', text: 'A bad hire who leaves or is dismissed at month four has been paid four months salary. For a role at 30,000 pounds per year, that is 10,000 pounds. During their notice period, productivity typically drops to near zero. That is another month of salary with no meaningful output.' },
      { type: 'h2', text: 'The hidden costs' },
      { type: 'h3', text: 'Management time' },
      { type: 'p', text: 'A struggling employee consumes disproportionate management time. Performance conversations, additional supervision, documentation of concerns, meetings with HR. A reasonable estimate is 5 to 10 hours per week of management time diverted to dealing with the problem. Over three months, at an average management hourly rate of 30 pounds, that is between 1,800 and 3,600 pounds.' },
      { type: 'h3', text: 'Team morale and productivity' },
      { type: 'p', text: 'When one person is underperforming, the rest of the team picks up the slack. They work harder, they become frustrated, and some of them start looking for other jobs. Research consistently shows that a single bad hire reduces the productivity of the immediate team by 10 to 15 per cent. For a team of five earning an average of 30,000 pounds, a 10 per cent productivity drop costs 15,000 pounds per year.' },
      { type: 'h3', text: 'Customer impact' },
      { type: 'p', text: 'If the bad hire is in a customer-facing role, the damage extends to client relationships. Lost customers, damaged reputation, reduced repeat business. This cost is almost impossible to quantify but is often the most significant of all.' },
      { type: 'h2', text: 'The new cost: tribunal risk under ERA 2025' },
      { type: 'p', text: 'From January 2027, add uncapped tribunal compensation to the list. Under the Employment Rights Act 2025, employees will have unfair dismissal protection from day one. The statutory compensation cap is being removed.' },
      { type: 'p', text: 'A tribunal award for unfair dismissal currently averages around 13,000 pounds, but without a cap, high-earning employees could claim significantly more. A senior hire on 80,000 pounds who is dismissed without proper documentation could claim 12 months salary or more. That is 80,000 pounds on top of all the other costs.' },
      { type: 'h2', text: 'The total' },
      { type: 'p', text: 'For a mid-level hire on 35,000 pounds:' },
      { type: 'p', text: 'Recruitment fees: 5,000 to 8,750 pounds. Advertising: 500 to 1,500 pounds. Training and onboarding: 3,000 to 8,000 pounds. Salary paid for unproductive work: 10,000 to 12,000 pounds. Management time: 1,800 to 3,600 pounds. Team productivity loss: 7,500 to 15,000 pounds. Potential tribunal claim from 2027: 13,000 to 80,000 pounds or more.' },
      { type: 'p', text: 'Total without tribunal: 27,800 to 48,850 pounds. Total with tribunal: 40,800 to 128,850 pounds.' },
      { type: 'p', text: 'The commonly cited figure of 30,000 to 50,000 pounds is at the lower end. For senior roles, or when tribunal claims are involved, the true cost can easily exceed 100,000 pounds.' },
      { type: 'h2', text: 'How to reduce the cost' },
      { type: 'p', text: 'The cheapest way to deal with a bad hire is to not make one in the first place. That sounds obvious, but most employers are still relying on CVs and interviews, both of which are poor predictors of job performance.' },
      { type: 'p', text: 'Scenario-based assessment, where candidates complete realistic work tasks specific to the role, has been shown to be significantly more predictive than traditional methods. It also creates the documented evidence trail that ERA 2025 will require.' },
      { type: 'p', text: 'The cost of a thorough pre-hire assessment is a tiny fraction of the cost of a bad hire. The question is not whether you can afford to assess candidates properly. The question is whether you can afford not to.' },
      { type: 'p', text: 'PRODICTA starts at 49 pounds per month. One prevented bad hire pays for 10 years of subscription. Try the free risk report tool at prodicta.co.uk.' },
    ],
  },

  {
    slug: 'why-interviews-dont-predict-job-performance',
    title: 'Why Interviews Do Not Predict Job Performance (And What Does)',
    date: '2026-04-09',
    dateLabel: '9 April 2026',
    metaDescription: 'Interviews measure confidence, not competence. Here is what actually predicts job performance and why scenario-based assessment is replacing traditional methods.',
    body: [
      { type: 'p', text: 'Interviews are the most widely used hiring tool in the world. They are also one of the least predictive.' },
      { type: 'p', text: 'That is not opinion. It is backed by decades of research. And yet most employers continue to make their most expensive decisions based on a 45-minute conversation where the candidate tells them exactly what they want to hear.' },
      { type: 'h2', text: 'The problem with interviews' },
      { type: 'h3', text: 'They measure the wrong thing' },
      { type: 'p', text: 'Interviews measure how someone performs under interview conditions. Not how they perform under work conditions. These are fundamentally different skills. The ability to articulate a clear answer to tell me about a time you handled conflict is not the same as the ability to actually handle conflict when it happens on a Tuesday afternoon with a deadline looming.' },
      { type: 'h3', text: 'They reward confidence, not competence' },
      { type: 'p', text: 'Confident candidates perform better in interviews. That is not controversial. But confidence and competence are not the same thing. The most confident person in the room is not necessarily the most capable. In fact, research suggests that overconfident candidates are more likely to overpromise and underdeliver, precisely because they overestimate their own abilities.' },
      { type: 'h3', text: 'They are inconsistent' },
      { type: 'p', text: 'Unless you use a rigidly structured interview format with identical questions and a standardised scoring rubric, different candidates are being assessed against different criteria by different interviewers in different moods on different days. The result is that the outcome depends as much on the interviewer as on the candidate.' },
      { type: 'h3', text: 'They are easy to prepare for' },
      { type: 'p', text: 'The internet is full of how to ace your interview guides. Candidates rehearse answers to common questions, practice their body language, and learn how to frame weaknesses as strengths. The best-prepared candidate wins the interview, but preparation for an interview is not the same as preparation for the job.' },
      { type: 'h2', text: 'What does predict job performance?' },
      { type: 'p', text: 'Research consistently identifies four things that predict whether someone will succeed in a role:' },
      { type: 'h3', text: '1. How they handle pressure when things go wrong' },
      { type: 'p', text: 'Not how they describe handling pressure in a hypothetical scenario, but how they actually respond when placed under realistic work pressure. Do they prioritise effectively? Do they maintain quality? Do they communicate clearly or go quiet?' },
      { type: 'h3', text: '2. Whether they follow through on commitments' },
      { type: 'p', text: 'Talk is cheap. Many candidates can articulate excellent plans and strategies. Far fewer actually follow through when the work gets hard, the deadline is tight, and nobody is watching. Execution reliability is one of the strongest predictors of probation success.' },
      { type: 'h3', text: '3. How they respond when the work is harder than expected' },
      { type: 'p', text: 'Every new job has a honeymoon period followed by a reality check. The candidates who succeed are the ones who adapt when the role turns out to be harder, more ambiguous, or more demanding than the job description suggested. The ones who fail are the ones who disengage.' },
      { type: 'h3', text: '4. Whether their working style matches the environment' },
      { type: 'p', text: 'A highly independent candidate in a highly collaborative team will struggle regardless of their technical skills. A process-driven candidate in a chaotic startup will be miserable within weeks. Matching working style to environment is as important as matching skills to requirements.' },
      { type: 'h2', text: 'The alternative: scenario-based assessment' },
      { type: 'p', text: 'Scenario-based assessment addresses every weakness of the traditional interview. Instead of asking candidates how they would handle a situation, it places them in the situation and measures how they actually respond.' },
      { type: 'p', text: 'The scenarios are built from the specific job description, not from generic templates. A care worker gets a safeguarding scenario. A finance director gets a board presentation under pressure. An office manager gets five competing demands landing on their desk at once.' },
      { type: 'p', text: 'The candidate completes the scenarios in their own time, on any device, in 15 to 45 minutes depending on the role level. Their responses are analysed for specificity, consistency, decision quality, pressure handling, and integrity.' },
      { type: 'p', text: 'The result is a documented, evidence-based prediction of how the candidate will actually perform in the first 90 days. Not how they say they will perform. How they actually respond when the work gets real.' },
      { type: 'h2', text: 'The compliance case' },
      { type: 'p', text: 'From January 2027, the Employment Rights Act 2025 requires employers to demonstrate that hiring decisions are fair, objective, and documented. An interview, even a well-structured one, produces subjective assessment notes that are difficult to defend in tribunal. A scenario-based assessment produces documented scores, backed by specific evidence from the candidate responses, tied directly to the job description.' },
      { type: 'p', text: 'The shift from interview-based to evidence-based hiring is not just a better way to hire. Under ERA 2025, it is becoming a compliance requirement.' },
      { type: 'p', text: 'PRODICTA uses scenario-based assessment to predict probation outcomes. Explore a demo report at prodicta.co.uk/demo.' },
    ],
  },

  {
    slug: 'how-to-prepare-for-day-one-unfair-dismissal-rights',
    title: 'How to Prepare for Day-One Unfair Dismissal Rights (January 2027)',
    date: '2026-04-09',
    dateLabel: '9 April 2026',
    metaDescription: 'From January 2027, unfair dismissal protection applies from day one. Here are 5 things every employer must do now to prepare.',
    body: [
      { type: 'p', text: 'In less than nine months, every employee in the UK will have unfair dismissal protection from their first day of employment. No qualifying period. No compensation cap. This is not a future possibility. It is confirmed legislation taking effect in January 2027.' },
      { type: 'p', text: 'If you are an employer, an HR professional, or a recruitment agency placing candidates, here is what you need to do now.' },
      { type: 'h2', text: 'What is changing' },
      { type: 'p', text: 'Currently, employees need two years of continuous service before they can bring an unfair dismissal claim. This gives employers a lengthy window during which they can terminate employment with relatively low risk.' },
      { type: 'p', text: 'From January 2027, that window shrinks to six months. The statutory compensation cap is also being removed. This means an employee dismissed after just six months could bring a claim with no upper limit on compensation.' },
      { type: 'p', text: 'The practical effect is that the probation period as most employers understand it, a low-risk window to assess a new hire, no longer exists in the same way. You can still have a probation period, but dismissing someone during it requires the same level of documentation and fairness as dismissing a long-serving employee.' },
      { type: 'h2', text: 'Five things to do before January 2027' },
      { type: 'h3', text: '1. Document your hiring criteria before you start recruiting' },
      { type: 'p', text: 'Before you advertise a role, write down exactly what you are looking for. Not vague qualities like good communicator or team player, but specific, measurable criteria tied to the job description. What tasks will this person perform? What skills are essential? What does success look like at 30, 60, and 90 days? This document becomes your evidence that the hiring decision was based on job-relevant criteria.' },
      { type: 'h3', text: '2. Use objective assessment methods' },
      { type: 'p', text: 'Move beyond CV screening and unstructured interviews. Use assessment methods that produce documented, evidence-based results. Scenario-based assessment, where candidates complete realistic work tasks, produces scores backed by specific evidence from the candidate responses. This creates an audit trail that demonstrates the hiring decision was objective and fair.' },
      { type: 'h3', text: '3. Generate a compliance certificate for every hire' },
      { type: 'p', text: 'Every hiring decision should be documented with: the assessment methodology used, the criteria against which candidates were evaluated, the evidence that led to the decision, and a statement confirming the process was fair and non-discriminatory. This document goes in the employee file and is your first line of defence if a tribunal claim is brought.' },
      { type: 'h3', text: '4. Structure your probation with documented milestones' },
      { type: 'p', text: 'Every new hire should have a structured probation plan with clear objectives at month one, three, and five. Regular documented check-ins should record what was expected, what was achieved, and what support was provided. If the employee is not meeting the required standard, the documentation should show that they were told, given specific guidance, and given a reasonable opportunity to improve.' },
      { type: 'h3', text: '5. Connect your assessment to your onboarding' },
      { type: 'p', text: 'The best approach is to use pre-hire assessment findings to shape the onboarding plan. If the assessment identified prioritisation as a development area, the onboarding plan should include specific support for prioritisation. If pressure handling was a concern, the plan should include structured check-ins during high-pressure periods. This creates a joined-up evidence trail from hire to probation completion.' },
      { type: 'h2', text: 'What if you need to dismiss someone?' },
      { type: 'p', text: 'Under the new rules, dismissing an employee during their first six months requires evidence of a fair process. You need to show: clear expectations were set from the start, regular feedback was provided, specific concerns were raised and documented, reasonable support was offered, and the employee was given a fair opportunity to improve.' },
      { type: 'p', text: 'If your hiring process produced documented assessment results, and your probation process included documented check-ins and support, you have a defensible position. If your hiring process consisted of good CV, nice in the interview and your probation process consisted of it just was not working out, you are exposed.' },
      { type: 'h2', text: 'The cost of waiting' },
      { type: 'p', text: 'Every hire you make between now and January 2027 will be tested under the new rules. A candidate hired in June 2026 reaches their six-month mark in December 2026. If something goes wrong, you are already operating under the new legislation.' },
      { type: 'p', text: 'The companies that prepare now will be protected. The companies that wait will be scrambling. Preparation is not expensive. An uncapped tribunal claim is.' },
      { type: 'p', text: 'PRODICTA generates ERA 2025 Compliance Certificates for every assessment. Start preparing at prodicta.co.uk.' },
    ],
  },

  {
    slug: 'scenario-based-assessment-vs-psychometric-testing',
    title: 'Scenario-Based Assessment vs Psychometric Testing: Which Actually Works?',
    date: '2026-04-10',
    dateLabel: '10 April 2026',
    metaDescription: 'Psychometric tests measure personality. Scenario-based assessment measures how people actually work. Here is an honest comparison.',
    body: [
      { type: 'p', text: 'If you are looking for a better way to assess candidates, you have probably come across two main approaches: psychometric testing and scenario-based assessment. Both claim to predict job performance. Both use technology. But they work in fundamentally different ways, and one is significantly more predictive than the other.' },
      { type: 'p', text: 'Here is an honest comparison.' },
      { type: 'h2', text: 'What is psychometric testing?' },
      { type: 'p', text: 'Psychometric tests measure psychological attributes: personality traits, cognitive ability, behavioural preferences, and emotional intelligence. The most common formats are multiple-choice questionnaires where candidates rate themselves on statements like I enjoy working in teams or I prefer structure to flexibility.' },
      { type: 'p', text: 'The results produce a personality profile or a set of trait scores. Common frameworks include the Big Five personality model, DISC profiling, Myers-Briggs, and various cognitive ability tests.' },
      { type: 'h2', text: 'What is scenario-based assessment?' },
      { type: 'p', text: 'Scenario-based assessment places candidates in realistic work situations and measures how they respond. Instead of asking do you prefer structure or flexibility, it gives the candidate a task that requires them to demonstrate how they handle structure, or the lack of it, in a situation specific to the role they are applying for.' },
      { type: 'p', text: 'The scenarios are built from the actual job description. A sales executive gets a pipeline pressure scenario. A care worker gets a safeguarding scenario. An office manager gets five competing demands landing at once. The candidate writes their response, and the assessment analyses their decision-making, communication, prioritisation, and pressure handling.' },
      { type: 'h2', text: 'The comparison' },
      { type: 'h3', text: 'What they measure' },
      { type: 'p', text: 'Psychometric tests measure how someone describes themselves. Scenario-based assessment measures how someone actually responds to work. These are different things. Most people describe themselves more favourably than they actually behave. This is not dishonesty. It is human nature. We all believe we handle pressure well until we are actually under pressure.' },
      { type: 'h3', text: 'Role specificity' },
      { type: 'p', text: 'Psychometric tests are generic. The same test is given to every candidate regardless of the role. A sales executive and a care worker take the same personality questionnaire. Scenario-based assessment is role-specific. Every assessment is built from the actual job description. The scenarios, the scoring criteria, and the predictions are all tailored to what this specific role requires.' },
      { type: 'h3', text: 'Evidence quality' },
      { type: 'p', text: 'Psychometric tests produce a profile: this person is high in conscientiousness and low in agreeableness. That is interesting but not actionable. Scenario-based assessment produces specific evidence: in scenario three, the candidate failed to complete the root cause analysis and missed two of the three required interventions. Under time pressure, task completion dropped significantly. That is actionable. It tells you exactly where the risk is and what to do about it.' },
      { type: 'h3', text: 'Fakability' },
      { type: 'p', text: 'Psychometric tests are easy to game. Candidates know that answering I enjoy working in teams positively is more likely to get them hired. The socially desirable answer is usually obvious. Scenario-based assessment is much harder to fake because the candidate has to actually demonstrate competence in a realistic situation. There is no obviously right answer to a multi-faceted work scenario.' },
      { type: 'h3', text: 'Compliance' },
      { type: 'p', text: 'From January 2027, the Employment Rights Act 2025 requires documented evidence of fair, objective, role-relevant hiring decisions. A personality profile that says high conscientiousness is difficult to tie to a specific job requirement. A scenario-based assessment that says the candidate scored 78 on prioritisation under load in a scenario designed to replicate the actual demands of this role is directly tied to the job description and produces documented evidence a tribunal can examine.' },
      { type: 'h2', text: 'When psychometric tests make sense' },
      { type: 'p', text: 'Psychometric tests are not useless. They have value in team development, coaching, and self-awareness exercises. If you want to help an existing team understand their communication preferences, a DISC profile can be useful. If you want to identify candidates for a leadership development programme, a cognitive ability test can help.' },
      { type: 'p', text: 'But for predicting whether a specific candidate will succeed in a specific role, psychometric tests fall short. They tell you how someone thinks about themselves. They do not tell you how they work.' },
      { type: 'h2', text: 'The bottom line' },
      { type: 'p', text: 'If your goal is to predict job performance, reduce hiring risk, and generate documented evidence for ERA 2025 compliance, scenario-based assessment is the stronger tool. It measures what actually matters: how candidates think, decide, and perform when the work gets real.' },
      { type: 'p', text: 'Personality tests tell you who someone says they are. Scenario-based assessment shows you who they actually are when it counts.' },
      { type: 'p', text: 'PRODICTA uses AI-powered scenario-based assessment to predict probation outcomes. See a real report at prodicta.co.uk/demo.' },
    ],
  },
]

export function getAllPosts() {
  return [...BLOG_POSTS].sort((a, b) => (a.date < b.date ? 1 : -1))
}

export function getPostBySlug(slug) {
  return BLOG_POSTS.find(p => p.slug === slug) || null
}

export function excerpt(post, words = 50) {
  const firstParagraph = post.body.find(b => b.type === 'p')?.text || ''
  const w = firstParagraph.split(/\s+/).slice(0, words)
  return w.join(' ') + (firstParagraph.split(/\s+/).length > words ? '...' : '')
}

export function readingTime(post) {
  const total = post.body.reduce((n, b) => n + (b.text || '').split(/\s+/).length, 0)
  return Math.max(1, Math.round(total / 220))
}
