'use client'

import { useState, useEffect, useSyncExternalStore } from 'react'
import { useRouter } from 'next/navigation'
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import Sidebar from '../../components/Sidebar'
import { Ic } from '../../components/Icons'
import { createClient } from '../../lib/supabase'
import { NAVY, TEAL, TEALD, TEALLT, BG, CARD, BD, TX, TX2, TX3, F, AMB, AMBBG, AMBBD, RED, REDBG, cs, bs } from '../../lib/constants'
import { TEMPLATES, CATEGORIES } from '../../lib/document-templates'

const _mSub = (cb) => { window.addEventListener('resize', cb); return () => window.removeEventListener('resize', cb) }
const _mSnap = () => window.innerWidth <= 768
const _mServer = () => false
function useIsMobile() { return useSyncExternalStore(_mSub, _mSnap, _mServer) }

export default function DocumentsPage() {
  const router = useRouter()
  const isMobile = useIsMobile()
  const [profile, setProfile] = useState(null)
  const [loading, setLoading] = useState(true)
  const [accountType, setAccountType] = useState('employer')
  const [selectedTemplate, setSelectedTemplate] = useState(null)
  const [fieldValues, setFieldValues] = useState({})
  const [generating, setGenerating] = useState(false)
  const [generated, setGenerated] = useState([])
  const [focusedField, setFocusedField] = useState(null)

  useEffect(() => {
    async function load() {
      const supabase = createClient()
      const { data: { user } } = await supabase.auth.getUser()
      if (!user) { router.push('/login'); return }
      const { data: prof } = await supabase.from('users').select('*').eq('id', user.id).single()
      setProfile(prof)
      setAccountType(prof?.account_type || 'employer')

      const { data: docs } = await supabase
        .from('generated_documents')
        .select('*')
        .eq('user_id', user.id)
        .order('generated_at', { ascending: false })
        .limit(20)
      setGenerated(docs || [])
      setLoading(false)
    }
    load()
  }, [])

  function selectTemplate(tpl) {
    const prefilled = {}
    if (tpl.prefilled.includes('worker_name')) prefilled.worker_name = ''
    if (tpl.prefilled.includes('company_name')) prefilled.company_name = profile?.company_name || ''
    if (tpl.prefilled.includes('role_title')) prefilled.role_title = ''
    if (tpl.prefilled.includes('client_company')) prefilled.client_company = ''
    if (tpl.prefilled.includes('start_date')) prefilled.start_date = ''
    if (tpl.prefilled.includes('end_date')) prefilled.end_date = ''
    if (tpl.prefilled.includes('return_date')) prefilled.return_date = ''
    if (tpl.prefilled.includes('sick_date')) prefilled.sick_date = ''
    if (tpl.prefilled.includes('absence_start_date')) prefilled.absence_start_date = ''
    tpl.required.forEach(r => { prefilled[r.key] = '' })
    setFieldValues(prefilled)
    setSelectedTemplate(tpl)
  }

  const allRequiredFilled = selectedTemplate ? selectedTemplate.required.every(r => fieldValues[r.key] && fieldValues[r.key].trim()) : false

  async function handleGenerate() {
    if (!selectedTemplate || !allRequiredFilled) return
    setGenerating(true)
    try {
      const text = selectedTemplate.body(fieldValues)

      // Generate PDF
      const pdf = await PDFDocument.create()
      const helvetica = await pdf.embedFont(StandardFonts.Helvetica)
      const bold = await pdf.embedFont(StandardFonts.HelveticaBold)
      const navy = rgb(0.06, 0.13, 0.22)
      const teal = rgb(0, 0.75, 0.65)
      const grey = rgb(0.37, 0.42, 0.50)
      const black = rgb(0.06, 0.09, 0.16)
      const white = rgb(1, 1, 1)
      const lightGrey = rgb(0.95, 0.96, 0.97)
      const PW = 595, PH = 842, ML = 48, TW = PW - 96

      function safe(t) { if (!t) return ''; return String(t).replace(/[\u2014\u2013]/g,', ').replace(/[\u2018\u2019]/g,"'").replace(/[\u201C\u201D]/g,'"').replace(/[\u2026]/g,'...').replace(/[^\x00-\xFF]/g,'') }
      function wrap(t, f, s, w) { const words = safe(t).split(/\s+/); const lines = []; let l = ''; for (const wd of words) { const test = l ? `${l} ${wd}` : wd; if (f.widthOfTextAtSize(test, s) > w) { if (l) lines.push(l); l = wd } else l = test } if (l) lines.push(l); return lines }

      let page = pdf.addPage([PW, PH])
      let y = PH - 48

      function checkPage(n) { if (y - n < 60) { page.drawText('Generated by PRODICTA | prodicta.co.uk', { x: ML, y: 30, size: 7, font: helvetica, color: grey }); page = pdf.addPage([PW, PH]); y = PH - 48 } }

      // Header
      page.drawRectangle({ x: 0, y: PH - 70, width: PW, height: 70, color: navy })
      page.drawText('PRO', { x: ML, y: PH - 48, size: 22, font: bold, color: white })
      page.drawText('DICTA', { x: ML + bold.widthOfTextAtSize('PRO', 22), y: PH - 48, size: 22, font: bold, color: teal })
      y = PH - 100

      // Title
      page.drawText(safe(selectedTemplate.name), { x: ML, y, size: 16, font: bold, color: navy }); y -= 20
      const dateStr = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
      page.drawText(`Generated: ${dateStr}`, { x: ML, y, size: 9, font: helvetica, color: grey }); y -= 20

      // Legal reference
      if (selectedTemplate.legal) {
        page.drawRectangle({ x: ML, y: y - 16, width: TW, height: 24, color: lightGrey })
        page.drawRectangle({ x: ML, y: y - 16, width: 3, height: 24, color: teal })
        page.drawText(safe(selectedTemplate.legal), { x: ML + 10, y: y - 6, size: 8, font: helvetica, color: grey })
        y -= 32
      }

      // Body text
      const bodyLines = text.split('\n')
      for (const line of bodyLines) {
        if (line.trim() === '') { y -= 10; continue }
        const isHeading = line === line.toUpperCase() && line.length > 3
        const font = isHeading ? bold : helvetica
        const size = isHeading ? 11 : 10
        const color = isHeading ? navy : black
        const wrapped = wrap(line, font, size, TW)
        for (const wl of wrapped) {
          checkPage(14)
          page.drawText(wl, { x: ML, y, size, font, color })
          y -= size + 4
        }
      }

      // Footer on all pages
      const footerText = `Generated by PRODICTA | prodicta.co.uk | ${dateStr}`
      for (const p of pdf.getPages()) {
        p.drawRectangle({ x: 0, y: 0, width: PW, height: 36, color: lightGrey })
        p.drawText(footerText, { x: ML, y: 14, size: 7, font: helvetica, color: grey })
      }

      // Download
      const bytes = await pdf.save()
      const blob = new Blob([bytes], { type: 'application/pdf' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${selectedTemplate.id}-${(fieldValues.worker_name || 'document').replace(/\s+/g, '-')}-${new Date().toISOString().slice(0, 10)}.pdf`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)

      // Save record
      const supabase = createClient()
      const { data: { user } } = await supabase.auth.getUser()
      if (user) {
        const { data: doc } = await supabase.from('generated_documents').insert({
          user_id: user.id,
          template_type: selectedTemplate.id,
          template_name: selectedTemplate.name,
          field_values: fieldValues,
        }).select('*').single()
        if (doc) setGenerated(prev => [doc, ...prev])
      }

      setSelectedTemplate(null)
      setFieldValues({})
    } catch (err) {
      console.error('Document generation error:', err)
    } finally {
      setGenerating(false)
    }
  }

  const inputStyle = (field) => ({
    fontFamily: F, fontSize: 14, width: '100%', padding: '10px 14px', borderRadius: 8,
    border: `1.5px solid ${focusedField === field ? TEAL : BD}`, background: CARD, color: TX,
    outline: 'none', transition: 'border-color 0.15s', boxSizing: 'border-box',
  })
  const requiredInputStyle = (field) => ({
    ...inputStyle(field),
    border: `1.5px solid ${focusedField === field ? TEAL : '#D97706'}`,
    background: fieldValues[field] ? CARD : '#fffbeb',
  })
  const labelStyle = { fontFamily: F, fontSize: 13, fontWeight: 600, color: TX, marginBottom: 6, display: 'block' }

  const visibleCategories = CATEGORIES.filter(c => !c.for || c.for === accountType)
  const visibleTemplates = TEMPLATES.filter(t => t.for === 'both' || t.for === accountType)

  if (loading) {
    return (
      <div style={{ display: 'flex', minHeight: '100vh', background: BG }}>
        <Sidebar active="documents" companyName="" />
        <main style={{ flex: 1, marginLeft: isMobile ? 0 : 220, marginTop: isMobile ? 56 : 0, padding: isMobile ? '24px 16px' : '36px 40px' }}>
          <div style={{ maxWidth: 900, margin: '0 auto', ...cs, height: 300, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <div style={{ width: 28, height: 28, border: `3px solid ${BD}`, borderTopColor: TEAL, borderRadius: '50%', animation: 'spin 0.7s linear infinite' }} />
          </div>
        </main>
      </div>
    )
  }

  return (
    <div style={{ display: 'flex', minHeight: '100vh', background: BG }}>
      <Sidebar active="documents" companyName={profile?.company_name || ''} />
      <main style={{ flex: 1, marginLeft: isMobile ? 0 : 220, marginTop: isMobile ? 56 : 0, padding: isMobile ? '24px 16px' : '36px 40px' }}>
        <div style={{ maxWidth: 900, margin: '0 auto' }}>
          <h1 style={{ fontFamily: F, fontSize: 22, fontWeight: 800, color: TX, margin: 0 }}>Document Templates</h1>
          <p style={{ fontFamily: F, fontSize: 14, color: TX2, margin: '6px 0 24px' }}>
            Generate pre-filled employment documents. All fields highlighted in amber must be completed before downloading.
          </p>

          {/* Disclaimer */}
          <div style={{ borderLeft: `4px solid ${AMB}`, background: AMBBG, borderRadius: '0 8px 8px 0', padding: '14px 18px', marginBottom: 24 }}>
            <p style={{ fontFamily: F, fontSize: 13, color: TX2, margin: 0, lineHeight: 1.55 }}>
              This template has been pre-filled using information held in PRODICTA. Review and complete all highlighted sections before sending. This document does not constitute legal advice. Seek independent employment law advice before issuing letters relating to dismissal, probation failure, or assignment termination.
            </p>
          </div>

          {/* Template generator form */}
          {selectedTemplate ? (
            <div style={{ ...cs, marginBottom: 24 }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16, flexWrap: 'wrap', gap: 8 }}>
                <h2 style={{ fontFamily: F, fontSize: 16, fontWeight: 700, color: TX, margin: 0 }}>{selectedTemplate.name}</h2>
                <button onClick={() => { setSelectedTemplate(null); setFieldValues({}) }} style={{ ...bs('secondary', 'sm') }}>Back to templates</button>
              </div>

              {selectedTemplate.warning && (
                <div style={{ background: REDBG, borderLeft: `4px solid ${RED}`, borderRadius: '0 8px 8px 0', padding: '12px 16px', marginBottom: 16 }}>
                  <p style={{ fontFamily: F, fontSize: 13, fontWeight: 700, color: RED, margin: 0 }}>{selectedTemplate.warning}</p>
                </div>
              )}

              {selectedTemplate.legal && (
                <div style={{ background: TEALLT, borderLeft: `4px solid ${TEAL}`, borderRadius: '0 8px 8px 0', padding: '10px 14px', marginBottom: 16 }}>
                  <p style={{ fontFamily: F, fontSize: 12, color: TX2, margin: 0 }}>{selectedTemplate.legal}</p>
                </div>
              )}

              {/* Pre-filled fields */}
              <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : '1fr 1fr', gap: 12, marginBottom: 16 }}>
                {selectedTemplate.prefilled.map(key => {
                  const label = key.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
                  return (
                    <div key={key}>
                      <label style={labelStyle}>{label}</label>
                      <input type={key.includes('date') ? 'date' : 'text'} value={fieldValues[key] || ''}
                        onChange={e => setFieldValues(prev => ({ ...prev, [key]: e.target.value }))}
                        onFocus={() => setFocusedField(key)} onBlur={() => setFocusedField(null)}
                        style={inputStyle(key)} />
                    </div>
                  )
                })}
              </div>

              {/* Required fields (amber) */}
              <div style={{ fontFamily: F, fontSize: 11, fontWeight: 700, color: AMB, textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 8 }}>Required fields</div>
              <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : '1fr 1fr', gap: 12, marginBottom: 20 }}>
                {selectedTemplate.required.map(r => (
                  <div key={r.key}>
                    <label style={{ ...labelStyle, color: fieldValues[r.key] ? TX : AMB }}>{r.label}</label>
                    {r.type === 'textarea' ? (
                      <textarea rows={3} value={fieldValues[r.key] || ''}
                        onChange={e => setFieldValues(prev => ({ ...prev, [r.key]: e.target.value }))}
                        onFocus={() => setFocusedField(r.key)} onBlur={() => setFocusedField(null)}
                        placeholder="[COMPLETE THIS SECTION]"
                        style={{ ...requiredInputStyle(r.key), resize: 'vertical' }} />
                    ) : r.type === 'select' ? (
                      <select value={fieldValues[r.key] || ''}
                        onChange={e => setFieldValues(prev => ({ ...prev, [r.key]: e.target.value }))}
                        style={{ ...requiredInputStyle(r.key), cursor: 'pointer' }}>
                        <option value="">[SELECT]</option>
                        {r.options.map(o => <option key={o} value={o}>{o}</option>)}
                      </select>
                    ) : (
                      <input type={r.type === 'date' ? 'date' : 'text'} value={fieldValues[r.key] || ''}
                        onChange={e => setFieldValues(prev => ({ ...prev, [r.key]: e.target.value }))}
                        onFocus={() => setFocusedField(r.key)} onBlur={() => setFocusedField(null)}
                        placeholder="[COMPLETE THIS SECTION]"
                        style={requiredInputStyle(r.key)} />
                    )}
                  </div>
                ))}
              </div>

              <button onClick={handleGenerate} disabled={!allRequiredFilled || generating}
                style={{
                  ...bs('primary', 'lg'), width: '100%', justifyContent: 'center',
                  opacity: (!allRequiredFilled || generating) ? 0.5 : 1,
                  cursor: (!allRequiredFilled || generating) ? 'not-allowed' : 'pointer',
                }}>
                {generating ? 'Generating...' : 'Download Document'}
                <Ic name="download" size={16} color={NAVY} />
              </button>
            </div>
          ) : (
            <>
              {/* Template library by category */}
              {visibleCategories.map(cat => {
                const templates = visibleTemplates.filter(t => t.category === cat.key)
                if (templates.length === 0) return null
                return (
                  <div key={cat.key} style={{ marginBottom: 24 }}>
                    <div style={{ fontFamily: F, fontSize: 11, fontWeight: 700, color: TX3, textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 10 }}>{cat.label}</div>
                    <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : 'repeat(auto-fill, minmax(260px, 1fr))', gap: 12 }}>
                      {templates.map(tpl => (
                        <div key={tpl.id} style={{ ...cs, padding: '16px 20px', display: 'flex', flexDirection: 'column', gap: 8 }}>
                          <div style={{ fontFamily: F, fontSize: 14, fontWeight: 700, color: TX }}>{tpl.name}</div>
                          <p style={{ fontFamily: F, fontSize: 12, color: TX3, margin: 0, lineHeight: 1.5, flex: 1 }}>{tpl.when}</p>
                          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                            <span style={{
                              fontSize: 10, fontWeight: 700, padding: '2px 8px', borderRadius: 20, fontFamily: F,
                              background: tpl.for === 'agency' ? TEALLT : tpl.for === 'employer' ? '#f0f4f8' : BG,
                              color: tpl.for === 'agency' ? TEALD : tpl.for === 'employer' ? NAVY : TX3,
                            }}>
                              {tpl.for === 'agency' ? 'Agency' : tpl.for === 'employer' ? 'Employer' : 'Both'}
                            </span>
                            <button onClick={() => selectTemplate(tpl)} style={{ ...bs('primary', 'sm') }}>Generate</button>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )
              })}

              {/* Recent documents */}
              {generated.length > 0 && (
                <div style={{ marginBottom: 24 }}>
                  <div style={{ fontFamily: F, fontSize: 11, fontWeight: 700, color: TX3, textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 10 }}>Recently generated</div>
                  <div style={{ ...cs, padding: 0, overflow: 'hidden' }}>
                    <div style={{ overflowX: 'auto' }}>
                      <table style={{ width: '100%', borderCollapse: 'collapse', fontFamily: F, fontSize: 13 }}>
                        <thead>
                          <tr style={{ background: BG }}>
                            {['Template', 'Date'].map(h => (
                              <th key={h} style={{ padding: '10px 14px', textAlign: 'left', fontWeight: 700, color: TX2, fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.3, borderBottom: `1px solid ${BD}` }}>{h}</th>
                            ))}
                          </tr>
                        </thead>
                        <tbody>
                          {generated.slice(0, 10).map((d, i) => (
                            <tr key={d.id} style={{ borderBottom: i < Math.min(generated.length, 10) - 1 ? `1px solid ${BD}` : 'none' }}>
                              <td style={{ padding: '10px 14px', fontWeight: 600, color: TX }}>{d.template_name}</td>
                              <td style={{ padding: '10px 14px', color: TX2 }}>{new Date(d.generated_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}</td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              )}
            </>
          )}
        </div>
      </main>
    </div>
  )
}
