-- Depth-Fit components launch.
--
-- Stores the shell+seniority-aware Day One Planning calendar and Inbox
-- Overload events the candidate sees during a Depth-Fit (or Strategy-Fit)
-- assessment. Generated at assessment-create time by
-- lib/depth-fit-components/.
--
-- Shape (see DEPTH_FIT_COMPONENTS_VERSION in
-- lib/depth-fit-components/_shared.js):
-- {
--   "version": "depth-fit-components-v1.0",
--   "generated_at": "ISO timestamp",
--   "shell_family": "office | healthcare | education",
--   "seniority": "junior | mid | manager | senior",
--   "day_one_planning": { fixed_events, interruption, deadline, unscheduled_tasks },
--   "inbox_overload":   { scenarios: [...] },
--   "diagnostics":      { ... per-generator metadata ... }
-- }
--
-- Existing assessments produced before this column existed continue to
-- read from the legacy assessments.calendar_events and
-- assessments.inbox_events columns via the reader fallback in
-- lib/depth-fit-components/index.js (readDayOnePlanning / readInboxOverload).

ALTER TABLE assessments
  ADD COLUMN IF NOT EXISTS depth_fit_components JSONB DEFAULT NULL;

COMMENT ON COLUMN assessments.depth_fit_components IS
  'Shell+seniority-aware Day One Planning calendar and Inbox Overload payload. '
  'Generated by lib/depth-fit-components/. NULL for assessments produced before '
  'this column existed; readers fall back to calendar_events / inbox_events.';
